spring:
  application:
    name: tarjetahabiente
server: 
  port: 8001
eureka: 
  client:
     serviceUrl:
      # Direccion a la que se conecta el microservicio con eureka
      defaultZone: http://localhost:8761/eureka
